import AppKit
import ApplicationServices
import Carbon.HIToolbox
import Foundation
import OSLog

/// Mete el texto transcripto en la app que tenía el foco.
///
/// No hay una API de macOS para "escribir en el campo de texto de otra app", así
/// que todo el mundo hace lo mismo: portapapeles + ⌘V sintético. Suena sencillo
/// y no lo es; casi todos los bugs conocidos de las apps de dictado viven acá.
/// Lo que sigue es la versión con las precauciones puestas:
///
/// - **El portapapeles es de la persona, no nuestro.** Se guarda lo que había y
///   se restaura después. La restauración va condicionada a un testigo propio:
///   si copió algo en el medio, no se le pisa.
/// - **No se puede dormir un tiempo fijo y asumir.** Escribir en el
///   `NSPasteboard` es asincrónico respecto de cuándo el resto del sistema lo
///   ve. Se sondea `changeCount` hasta confirmar que la escritura tomó.
/// - **`⌘V` no siempre es la tecla 9.** Ese keycode es "V" en QWERTY; en Dvorak
///   o AZERTY es otra. Se resuelve contra la distribución activa.
/// - **Secure Input.** Cuando hay un campo de contraseña enfocado, macOS bloquea
///   los eventos sintéticos. Se detecta antes y se avisa, en vez de "no pasa
///   nada" sin explicación.
/// - **El foco se mueve.** Entre que se suelta la tecla y termina la
///   transcripción pasan cientos de milisegundos en los que la persona puede
///   haber cambiado de ventana. Se compara contra la app capturada al arrancar
///   y, si cambió, no se pega a ciegas.
@MainActor
final class TextInjector {

    /// Cómo terminó el intento de inserción. La UI necesita distinguirlos: cada
    /// uno se le comunica distinto a la persona.
    enum Outcome: Sendable, Equatable {
        /// Se pegó en la app de destino.
        case inserted
        /// No se pudo pegar; el texto quedó en el portapapeles.
        case copiedToClipboard(reason: FallbackReason)
    }

    enum FallbackReason: Sendable, Equatable {
        case secureInputActive(process: String?)
        case focusChanged(from: String?, to: String?)
        case noAccessibilityPermission
        case pasteFailed

        var message: String {
            switch self {
            case .secureInputActive(let process):
                if let process {
                    return String(localized: "\(process) tiene activada la entrada segura. El texto quedó en el portapapeles: pegalo con ⌘V.")
                }
                return String(localized: "Hay un campo de contraseña activo. El texto quedó en el portapapeles: pegalo con ⌘V.")
            case .focusChanged:
                return String(localized: "Cambiaste de app mientras se transcribía. El texto quedó en el portapapeles: pegalo con ⌘V.")
            case .noAccessibilityPermission:
                return String(localized: "Falta el permiso de Accesibilidad. El texto quedó en el portapapeles: pegalo con ⌘V.")
            case .pasteFailed:
                return String(localized: "No se pudo pegar en esta app. El texto quedó en el portapapeles: pegalo con ⌘V.")
            }
        }
    }

    /// Identidad de la app de destino, capturada cuando arranca el dictado.
    struct Target: Sendable, Equatable {
        let bundleIdentifier: String?
        let processIdentifier: pid_t
        let localizedName: String?

        static func current() -> Target? {
            guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
            return Target(
                bundleIdentifier: app.bundleIdentifier,
                processIdentifier: app.processIdentifier,
                localizedName: app.localizedName
            )
        }
    }

    /// Tipos que le avisan a los gestores de portapapeles (Maccy, Raycast, Paste)
    /// que esto es tránsito y no vale la pena archivarlo. Sin esto, cada dictado
    /// queda guardado para siempre en el historial de otra app — que es
    /// exactamente lo contrario de lo que promete una app local.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Marca privada para reconocer que lo que está en el portapapeles sigue
    /// siendo nuestro cuando llega el momento de restaurar.
    private static let sessionType = NSPasteboard.PasteboardType("com.acti.susurro.session")

    private let pasteboard = NSPasteboard.general
    private let logger = Logger(subsystem: "com.acti.susurro", category: "TextInjector")

    /// Keycode de la "V" en la distribución de teclado activa. Se recalcula
    /// cuando cambia la fuente de entrada.
    private var cachedPasteKeyCode: CGKeyCode?

    /// Si se devuelve el portapapeles a como estaba después de pegar.
    ///
    /// Es configurable porque desde macOS 15.4 *leer* el portapapeles por
    /// programa puede disparar una alerta del sistema — y para restaurar hay
    /// que leer primero. Cuando la persona ya denegó ese acceso, no tiene
    /// sentido intentarlo: se deja el texto en el portapapeles y listo.
    var restoresClipboard: Bool = true {
        didSet { logger.debug("restauración de portapapeles: \(self.restoresClipboard)") }
    }

    /// Si macOS va a dejar leer el portapapeles sin molestar a la persona.
    static var clipboardReadIsPermitted: Bool {
        guard #available(macOS 15.4, *) else { return true }
        switch NSPasteboard.general.accessBehavior {
        case .alwaysDeny:
            return false
        default:
            // `.default` y `.ask` pueden mostrar una alerta la primera vez, pero
            // es una sola vez y la alternativa —pisarle el portapapeles sin
            // avisar— es peor. `.alwaysAllow` no pregunta nada.
            return true
        }
    }

    init() {
        restoresClipboard = Self.clipboardReadIsPermitted

        NotificationCenter.default.addObserver(
            forName: NSTextInputContext.keyboardSelectionDidChangeNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            MainActor.assumeIsolated { self?.cachedPasteKeyCode = nil }
        }
    }

    // MARK: - API

    /// Inserta `text` en `target`, o lo deja en el portapapeles explicando por qué.
    func insert(_ text: String, into target: Target?) async -> Outcome {
        guard !text.isEmpty else { return .inserted }

        // Secure Input se chequea primero: con un campo de contraseña enfocado
        // los eventos sintéticos se descartan en silencio, así que ni vale la
        // pena intentar.
        if IsSecureEventInputEnabled() {
            let owner = Self.secureInputOwner()
            logger.notice("secure input activo (\(owner ?? "desconocido", privacy: .public)); no se pega")
            place(text, markingTransient: false)
            return .copiedToClipboard(reason: .secureInputActive(process: owner))
        }

        // Sin permiso de Accesibilidad, `CGEvent.post` no falla: simplemente no
        // hace nada. Hay que preguntar antes para poder explicarlo.
        guard AXIsProcessTrusted() else {
            logger.notice("sin permiso de accesibilidad; no se pega")
            place(text, markingTransient: false)
            return .copiedToClipboard(reason: .noAccessibilityPermission)
        }

        // ¿Sigue adelante la misma app que cuando se empezó a dictar?
        let now = Target.current()
        if let target, let now, now.processIdentifier != target.processIdentifier {
            logger.notice("el foco cambió de \(target.localizedName ?? "?", privacy: .public) a \(now.localizedName ?? "?", privacy: .public)")
            place(text, markingTransient: false)
            return .copiedToClipboard(
                reason: .focusChanged(from: target.localizedName, to: now.localizedName))
        }

        let snapshot = restoresClipboard ? ClipboardSnapshot(pasteboard) : nil
        let token = UUID().uuidString

        guard place(text, markingTransient: true, token: token) else {
            logger.error("el portapapeles no aceptó la escritura")
            return .copiedToClipboard(reason: .pasteFailed)
        }

        let pasted = postPasteShortcut()

        // Se le da a la app de destino un margen para consumir el portapapeles
        // antes de devolverlo a como estaba. Menos de ~250 ms y las apps lentas
        // (Electron, sobre todo) llegan a pegar el contenido viejo.
        if let snapshot {
            try? await Task.sleep(for: .milliseconds(400))
            restore(snapshot, ifStillOurs: token)
        }

        if pasted {
            return .inserted
        }

        // Último recurso: escribir el texto directo en el elemento enfocado vía
        // la API de Accesibilidad. Funciona en apps AppKit nativas y falla en
        // las que se dibujan solas (Electron, terminales), por eso va segundo.
        if insertViaAccessibility(text) {
            return .inserted
        }

        place(text, markingTransient: false)
        return .copiedToClipboard(reason: .pasteFailed)
    }

    /// Deja el texto en el portapapeles sin intentar pegarlo.
    func copyOnly(_ text: String) {
        place(text, markingTransient: false)
    }

    // MARK: - Portapapeles

    private struct ClipboardSnapshot {
        let changeCount: Int
        let items: [[NSPasteboard.PasteboardType: Data]]

        init(_ pasteboard: NSPasteboard) {
            changeCount = pasteboard.changeCount
            items = (pasteboard.pasteboardItems ?? []).map { item in
                var stored: [NSPasteboard.PasteboardType: Data] = [:]
                for type in item.types {
                    if let data = item.data(forType: type) {
                        stored[type] = data
                    }
                }
                return stored
            }
        }
    }

    /// Escribe en el portapapeles y confirma que la escritura realmente tomó.
    @discardableResult
    private func place(_ text: String, markingTransient: Bool, token: String? = nil) -> Bool {
        let before = pasteboard.changeCount
        pasteboard.clearContents()

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if markingTransient {
            // Vacío a propósito: la convención de nspasteboard.org define estos
            // tipos como banderas, el valor no importa.
            item.setString("", forType: Self.transientType)
            item.setString("", forType: Self.autoGeneratedType)
            item.setString("Susurro", forType: Self.sourceType)
            if let token {
                item.setString(token, forType: Self.sessionType)
            }
        }
        pasteboard.writeObjects([item])

        // `changeCount` es la única señal confiable de que el pasteboard server
        // procesó la escritura. Dormir un rato fijo es lo que produce el bug
        // clásico de "me pegó lo que tenía copiado antes".
        return pasteboard.changeCount != before
    }

    private func restore(_ snapshot: ClipboardSnapshot, ifStillOurs token: String) {
        // Si el contenido ya no es el nuestro, la persona copió algo mientras
        // tanto. Restaurar ahí sería destruir su copia.
        guard pasteboard.string(forType: Self.sessionType) == token else {
            logger.debug("el portapapeles cambió durante el pegado; no se restaura")
            return
        }

        pasteboard.clearContents()
        guard !snapshot.items.isEmpty else { return }

        let restored = snapshot.items.map { stored -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in stored {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(restored)
    }

    // MARK: - Pegado sintético

    private func postPasteShortcut() -> Bool {
        guard let keyCode = pasteKeyCode() else {
            logger.error("no se encontró la tecla V en la distribución activa")
            return false
        }

        // `.combinedSessionState` hace que los eventos hereden el estado real
        // del teclado; después se fuerzan las banderas para que el modificador
        // que la persona todavía puede tener apretado (⌥ derecho, por ejemplo)
        // no se cuele en el ⌘V.
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else {
            return false
        }

        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand

        keyDown.post(tap: .cgAnnotatedSessionEventTap)
        keyUp.post(tap: .cgAnnotatedSessionEventTap)
        return true
    }

    /// Busca el keycode que produce "v" en la distribución de teclado activa.
    ///
    /// Hardcodear `kVK_ANSI_V` (9) rompe en Dvorak, AZERTY y varias
    /// distribuciones más: ahí el 9 es otra letra y el atajo termina siendo
    /// ⌘ con-lo-que-sea. Se traduce cada keycode con la distribución real y se
    /// busca cuál da "v".
    private func pasteKeyCode() -> CGKeyCode? {
        if let cachedPasteKeyCode { return cachedPasteKeyCode }

        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let layoutPointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)
        else {
            cachedPasteKeyCode = CGKeyCode(kVK_ANSI_V)
            return cachedPasteKeyCode
        }

        let layoutData = Unmanaged<CFData>.fromOpaque(layoutPointer).takeUnretainedValue() as Data

        let found: CGKeyCode? = layoutData.withUnsafeBytes { raw -> CGKeyCode? in
            guard let base = raw.baseAddress else { return nil }
            let layout = base.assumingMemoryBound(to: UCKeyboardLayout.self)

            for code in 0..<CGKeyCode(128) {
                var deadKeyState: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)

                let status = UCKeyTranslate(
                    layout,
                    UInt16(code),
                    UInt16(kUCKeyActionDown),
                    0,  // sin modificadores
                    UInt32(LMGetKbdType()),
                    OptionBits(kUCKeyTranslateNoDeadKeysMask),
                    &deadKeyState,
                    chars.count,
                    &length,
                    &chars
                )

                guard status == noErr, length > 0 else { continue }
                if String(utf16CodeUnits: chars, count: length).lowercased() == "v" {
                    return code
                }
            }
            return nil
        }

        cachedPasteKeyCode = found ?? CGKeyCode(kVK_ANSI_V)
        return cachedPasteKeyCode
    }

    // MARK: - Plan B: API de Accesibilidad

    /// Escribe directo en el campo enfocado. Anda en apps AppKit nativas;
    /// las que renderizan su propio texto (Electron, VS Code, terminales)
    /// suelen no exponer un `AXTextArea` escribible, y ahí devuelve `false`.
    private func insertViaAccessibility(_ text: String) -> Bool {
        let system = AXUIElementCreateSystemWide()
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
            system, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
            let element = focused
        else { return false }

        // swiftlint:disable:next force_cast
        let axElement = element as! AXUIElement

        // Reemplaza la selección actual, que con el cursor sin seleccionar nada
        // equivale a insertar en el punto de inserción.
        let status = AXUIElementSetAttributeValue(
            axElement, kAXSelectedTextAttribute as CFString, text as CFTypeRef)

        if status == .success {
            logger.debug("insertado vía API de accesibilidad")
            return true
        }
        return false
    }

    // MARK: - Secure Input

    /// Qué proceso dejó activada la entrada segura.
    ///
    /// Saber el nombre es la diferencia entre «no funciona» y «1Password está
    /// bloqueando el pegado». No hay API pública: el PID dueño del secure input
    /// aparece en el registro de IOKit como `kCGSSessionSecureInputPID`.
    ///
    /// (Verificado en esta máquina: *no* está en `CGSessionCopyCurrentDictionary()`,
    /// que es donde uno esperaría encontrarlo — ese diccionario solo trae las
    /// claves de sesión y bloqueo de pantalla. Hay que ir a `ioreg`.)
    ///
    /// Solo se consulta cuando ya se sabe que el secure input está activo, que
    /// es raro, así que el costo de lanzar un proceso no importa.
    private static func secureInputOwner() -> String? {
        guard let pid = secureInputPID(), pid > 0 else { return nil }
        if let app = NSRunningApplication(processIdentifier: pid) {
            return app.localizedName
        }
        // Los procesos sin interfaz (loginwindow, agentes de fondo) no aparecen
        // como NSRunningApplication; ahí se cae al nombre del ejecutable.
        return processName(pid: pid)
    }

    private static func secureInputPID() -> pid_t? {
        let output = run("/usr/sbin/ioreg", ["-l", "-w", "0", "-d", "1"])
        guard let line = output?
            .split(separator: "\n")
            .first(where: { $0.contains("kCGSSessionSecureInputPID") })
        else { return nil }

        let digits = line.split(separator: "=").last?
            .trimmingCharacters(in: .whitespaces)
            .prefix(while: \.isNumber)
        return digits.flatMap { pid_t($0) }
    }

    private static func processName(pid: pid_t) -> String? {
        run("/bin/ps", ["-o", "comm=", "-p", String(pid)])?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .split(separator: "/").last
            .map(String.init)
    }

    private static func run(_ path: String, _ arguments: [String]) -> String? {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: path)
        process.arguments = arguments
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = FileHandle.nullDevice
        do {
            try process.run()
        } catch {
            return nil
        }
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        return String(data: data, encoding: .utf8)
    }
}
